#!/bin/sh
# Jien's profile.

export_loop(){
	# Chore, because I'm lazy to type "export" so many times.
	# Standard "export" command takes arguments
	#	from variables from the start, but I want to
	#	use other variables in definition for next of them.
	while [  ! -z "$1" ]  ; do
		# Doing until we have arguments.
		value="$(eval echo $2)"
		name="$1"
		export "$name"="$value"
		shift 2
	done
}

# Standard variables.
export_loop ENVDIR "$HOME/env" \
	SETENV '$HOME/.setenv' \
	SHPROMPT '"; "' \
	PS1 '"$SHPROMPT"' \
	SUDO_PROMPT '"#"' \
	EDITOR 'ed' \
	GIT_EDITOR '$EDITOR' \
	PAGER 'more' \
	MANPAGER '$PAGER' \
	GOPATH '$HOME/go' \
	PROFILE '$HOME/.profile' \
	ENV '$HOME/.shrc' \
	ETC '$HOME/etc' \
	LIB '$HOME/lib' \
	GIT '$HOME/git' \
	SHR '$HOME/shr' \
	SHARED '$HOME/shared' \
	LOCAL '$HOME/local' \
	BIN '$LOCAL/bin' \
	TMPS '$HOME/tmps' \
	TMP '$HOME/tmp' \
	MNT '$LOCAL/mnt' \
	ATK '$TMP/atk' \
	IMG '$HOME/img' \
	AUDIO '$HOME/audio' \
	DOC '$HOME/doc' \
	VIDEO '$HOME/video' \
	DOWNLOAD '$HOME/download' \
	INFERNO '$HOME/inferno' \
	PLAN9 '$HOME/plan9' \
	IRRLICHT '$HOME/irrlicht' \
	XINITRC '$HOME/.xinitrc' \
	XRESOURCES '$HOME/.Xresources' \
	XMODMAP '$HOME/.Xmodmap' \
	XDG_CONFIG_HOME '$HOME/.config' \
	XDG_RUNTIME_DIR '$TMP' \
	LOGIN '$HOME/.login' \
	ZSHRC '$HOME/.zshrc' \
	BASHRC '$HOME/.bashrc' \
	SHRC '$ENV' \
	PATH '$BIN:$GOPATH/bin:$PATH:$PLAN9/bin' \

	# No visual, because I should set it by the hand, depending on system,
	# or not set it at all.
	# Because it sucks.

. "$SETENV.sh"
setenv profile
