#!/bin/sh
# Jien's profile.

export_loop(){
	# Chore, because I'm lazy to type "export" so many times.
	# Standard "export" command takes arguments
	#	from variables from the start, but I want to
	#	use other variables in definition for next of them.
	while [  ! -z "$1" ]  ; do
		# Doing until we have arguments.
		value="$(eval echo $2)"
		name="$1"
		export "$name"="$value"
		shift 2
	done
}

# Standard variables.
export_loop  \
	ENV '$HOME/.shrc' \
	SHPROMPT '"% "' \
	PS1 '"$SHPROMPT"' \
	SUDO_PROMPT '"#"' \
	EDITOR 'ed' \
	VISUAL 'vi' \
	GIT_EDITOR '$VISUAL' \
	PAGER 'more' \
	MANPAGER '$PAGER' \
	PROFILE '$HOME/.profile' \
	TXT '$HOME/txt' \
	SHARED '$HOME/shared' \
	TMPS '$HOME/tmps' \
	LOCAL '$HOME/local' \
	ENVDIR '$LOCAL/env' \
	GIT '$LOCAL/git' \
	ETC '$LOCAL/etc' \
	SETENV '$ETC/env/setenv' \
	TMP '$LOCAL/tmp' \
	SHR '$LOCAL/shr' \
	MNT '$LOCAL/mnt' \
	BIN '$LOCAL/bin' \
	GOPATH '$LOCAL/go' \
	PLAN9BASE '/usr/local/plan9' \
	PLAN9PORT '$LOCAL/plan9' \
	PLAN9 '$PLAN9PORT' \
	INFERNO '$LOCAL/inferno' \
	LIB '$HOME/lib' \
	IMG '$HOME/img' \
	AUDIO '$HOME/audio' \
	DOC '$HOME/doc' \
	VIDEO '$HOME/video' \
	DOWNLOAD '$HOME/download' \
	IRRLICHT '$LOCAL/irrlicht' \
	RAYLIB '$LOCAL/raylib' \
	XINITRC '$HOME/.xinitrc' \
	XRESOURCES '$HOME/.Xresources' \
	XMODMAP '$HOME/.Xmodmap' \
	XDG_CONFIG_HOME '$LIB' \
	XDG_RUNTIME_DIR '$TMP' \
	LOGIN '$HOME/.login' \
	ZSHRC '$HOME/.zshrc' \
	BASHRC '$HOME/.bashrc' \
	SHRC '$ENV' \
	PATH '$BIN:$GOPATH/bin:$PATH:$PLAN9BASE/bin:$PLAN9PORT/bin' \

. "$SETENV.sh"
setenv profile
