exec $@


session="${1:-$XWM}"
shift
arg="$@"

# Here a can add specific options for ever WM, DE and
# any other program I want start with Xorg.
case "$session" in
	#session{{{
	awesome ) exec awesome $arg ;;
	bspwm ) exec bspwm $arg ;;
	catwm ) exec catwm $arg ;;
	cinnamon ) exec cinnamon-session $arg ;;
	vvm | wm | flwm| jdwm | dwm | rio )
		export CURWM="$session"
		wmrc "$session"
		exec $session $arg
	;;
	enlightenment ) exec enlightenment_start;;
	ede ) exec startede $arg ;;
	fluxbox ) exec startfluxbox $arg ;;
	gnome ) exec gnome-session $arg ;;
	gnome-classic ) exec gnome-session --session=gnome-classic $arg ;;
	i3 ) exec i3 $arg ;;
	icewm ) exec icewm-session $arg ;;
	jwm ) exec jwm $arg ;;
	kde ) exec startkde $arg ;;
	mate ) exec mate-session $arg ;;
	monster|monsterwm ) exec monsterwm $arg ;;
	notion ) exec notion $arg ;;
	openbox ) exec openbox-session $arg ;;
	unity ) exec unity $arg ;;
	xfce|xfce4|startxfce4 ) exec startxfce4 $arg ;;
	xmonad            ) exec xmonad $arg ;;
	# Not found any specific options case.
	*) exec $session $arg ;;
	#session}}}
esac
