#!/bin/sh
# Jien's zshrc.
if test -r"$LOGIN.sh" ; then
	. "$LOGIN.sh"
fi
autoload -Uz compinit promptinit
compinit
promptinit
zstyle ':completion:*' menu select
zstyle ':completion:*:manuals' separate-sections true
zstyle ':completion:*:manuals.*' insert-sections true
zstyle ':completion:*:man:*' menu yes select
setopt correct
# History configuration.
zshaddhistory() { whence ${${(z)1}[1]} >| /dev/null || return 1 }
HISTFILE="$HOME/.zhistory"
HISTSIZE=10000
SAVEHIST="$HISTSIZE"
# Other stuff.
setopt menu_complete
setopt append_history
setopt extended_history
setopt inc_append_history
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt no_hist_beep
setopt auto_cd
setopt nonomatch
setopt notify
setopt hash_list_all
setopt nohup
setopt nobeep
setopt noglobdots
setopt noshwordsplit
# Prompt.
PROMPT="$SHPROMPT"
# Bindings.
new-backward-delete-word() {
    local WORDCHARS=${WORDCHARS/\//}
    zle backward-delete-word
}
zle -N new-backward-delete-word
bindkey '^W' new-backward-delete-word
zle -N zle-keymap-select
export KEYTIMEOUT=1

ZSH_AUTOSUGGEST_STRATEGY="history"
zle -N autosuggest-accept
bindkey '^ ' autosuggest-accept
# Plugins.
set -A plugin_dirs \
	"/usr/share/" \
	"/usr/share/zsh/plugins"
set -A plugins \
	syntax-highlighting \
	autosuggestions
for plugin in $plugins ; do
	for dir in $plugin_dirs ; do
		file="$dir/zsh-$plugin/zsh-$plugin.zsh"
		if [ -f $file ] ; then
			. "$file"
			break
		fi
	done
done
# grc
set -A grc_progs \
	cat cvs df digg gcc g++ ls ifconfig \
	make mount mtr netstat ping ps tail \
	traceroute wdiff blkid du dnf docker \
	docker-machine env id ip iostat last \
	lsattr lsblk lspci lsmod lsof getfacl\
	getsebool ulimit uptime nmap fdisk findmnt\
	free semanage sar ss sysctl systemctl stat showmount\
	tune2fs tcpdump
# Set enviroment.
if test -r "$SETENV.sh" ; then
	. "$SETENV.sh"
	setenv zsh
fi
