session=${1:-dwm}

case $session in
	awesome           ) exec awesome;;
	bspwm             ) exec bspwm;;
	catwm             ) exec catwm;;
	cinnamon          ) exec cinnamon-session;;
	dwm               )
		setxkbmap -layout us,ru -variant dvorak, -option grp:alt_space_toggle
		xrdb -load ~/.Xresources
		xset r rate 300 57
		slstatus &
		if [ -s ~/.Xmodmap ] ; then
			xmodmap ~/.Xmodmap
		fi
		exec dwm;;
	rio               ) exet rio;;
	enlightenment     ) exec enlightenment_start;;
	ede               ) exec startede;;
	fluxbox           ) exec startfluxbox;;
	gnome             ) exec gnome-session;;
	gnome-classic     ) exec gnome-session --session=gnome-classic;;
	i3|i3wm           ) exec i3;;
	icewm             ) exec icewm-session;;
	jwm               ) exec jwm;;
	kde               ) exec startkde;;
	mate              ) exec mate-session;;
	monster|monsterwm ) exec monsterwm;;
	notion            ) exec notion;;
	openbox           ) exec openbox-session;;
	unity             ) exec unity;;
	xfce|xfce4        ) exec startxfce4;;
	xmonad            ) exec xmonad;;
	*) exec $1;;
esac
