#!/bin/sh
menu="$XMENU"
case "`basename $menu`" in
	dmenu | jdmenu )
		cmd=" ` path | menu -p '$RUNMENUPROMPT' -m '$1'  ` "
		[ -z $cmd ] && exit
		exec $cmd
	;;
	* )
		cmd=" ` path | menu ` "
		[ -z $cmd ] && exit
		exec $cmd
	;;
esac
