#!/bin/sh

menu="$XMENU"
case "`basename $menu`" in
	dmenu | jdmenu )
		cmd=" ` path | menu -p '$ITEMENUPROMPT' -m '$1'  ` "
		[ -z $cmd ] && exit
		exec ite $cmd
	;;
	* )
		cmd=" ` path | menu ` "
		[ -z $cmd ] && exit
		exec ite $cmd
	;;
esac
