#!/bin/sh
# Wrapper to call stream edition commands.
usage(){
	echo "Usage of $0:" >&2
	echo "\t$0 [command] [arguments]" >&2
}
abort(){
	exit 1
}
if [ "${#@}" = 0 ] ; then
	usage
	abort
fi
prog="$1"
shift

cd $SEUTILS
exec ./$prog $@
