#!/bin/sh
# Wrapper for any dumbness terminal.
term="$XTERMINAL"

case "`basename $term`" in
	cli_dumb )
		exec "$term" shell
	;;
	st | jst )
		exec "$term" $@
	;;
	9term )
		exec "$term" $@
	;;
	* )
		exec it -e "$@"
	;;
esac

