#!/bin/sh
# Wrapper for terminal calls to be easy to use any terminal.
# Yeap, I love hacks.

# If X is running, now I don't know how to diverse Wayland and Xorg.
# I should resolve it later.
case "`basename $XTERMINAL`" in
	9term )
		exec "$XTERMINAL" $@
	;;
	st )
		exec "$XTERMINAL" -e $@
	;;
	jst )
		exec "$XTERMINAL"  -e $@
	;;
	* )
		exec "XTERMINAL" -e "$@"
	;;
esac
