#!/bin/sh
# Wrapper for terminal calls to be easy to use any terminal.
# Yeap, I love hacks.
term="$XTERMINAL"
# If X is running, now I don't know how to diverse Wayland and Xorg.
# I should resolve it later.
case "`basename $term`" in
	cli_dumb )
		exec t "$@"
	;;
	9term )
		exec t $@
	;;
	st | jst )
		exec t -e $@
	;;
	* )
		exec t -e "$@"
	;;
esac
