#!/bin/sh
# Wrapper for terminal session managers to create new session.

tsm="$TERMINAL_SESSION_MANAGER"
case "`basename $tsm`" in
	tmux )
		exec $tsm new-session $@
	;;
	screen )
		exec $tsm $@
	;;
	* )
		exec $tsm $@
	;;
esac
