#!/bin/sh
# Visual editor wrapper.
case "`basename $VISUAL`" in
	edwood )
		exec "$VISUAL" -m "$ACMEMNT"
	;;
	acme )
		exec "$VISUAL"
	;;
	sam )
		exec "$VISUAL"
	;;
	gvim )
		exec "$VISUAL"
	;;
	adie )
		exec "$VISUAL"
	;;
	* )
		exec "$VISUAL"
	;;
esac
