#!/bin/sh
# Wrapper to call run command for exact WM.

wm="${1:-$CURWM}"

echo $wm
case "$wm" in
	 dwm )
		setxkbmap $DVORAK_KEYBOARD_LAYOUT
		xrdb -merge "$XRESOURCES"
		xset r rate "$KEYBOARD_REPEAT_DELAY" "$KEYBOARD_REPEAT_RATE"
		killall "$XSTATUS"
		eval "$XSTATUS" &
		if [ -s "$XMODMAP" ] ; then
			xmodmap "$XMODMAP" 
		fi
	;;
	 vvm | jdwm | wm | flwm)
		setxkbmap $DVORAK_KEYBOARD_LAYOUT
		xrdb -merge "$XRESOURCES"
		xset r rate "$KEYBOARD_REPEAT_DELAY" "$KEYBOARD_REPEAT_RATE"
		if [ -s "$XMODMAP" ] ; then
			xmodmap "$XMODMAP" 
		fi
	;;
	* )
		# Nothing.
	;;
esac
